Update projects page
open-mmlab/mmclassification pull request #1003
Opened 2022-08-30 04:05 UTC by tonysy

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-30 06:30 UTC, Ezra-Yu commented on docs/en/notes/projects.md
> +- [OpenBioSeq](https://github.com/Westlake-AI/OpenBioSeq): an open-source supervised and self-supervised bio-sequence representation learning toolbox based on PyTorch.
- [ConvolutionOfConvolution(CVPR2022)](https://github.com/Genera1Z/ConvolutionOfConvolution):  an algorithm that associates kernels in a layer and lets them collaborate spatially.

this work can be added here too.

2022-08-31 03:08 UTC, mzr1996 requested changes

2022-08-31 03:08 UTC, mzr1996 commented on docs/en/notes/projects.md
> +To make this list also a reference for the community to develop and compare new object detection algorithms, we list them following the time order of top-tier conferences.
object detection -> image classification

2022-08-31 06:06 UTC, mzr1996 approved these changes

2022-08-31 06:07 UTC, merged