[Feature] Support HorNet
open-mmlab/mmclassification pull request #1013
Opened 2022-09-05 05:19 UTC by okotaku

## Motivation

[HorNet: Efficient High-Order Spatial Interactions with Recursive Gated Convolutions(https://arxiv.org/pdf/2207.14284v2.pdf)
[github](https://github.com/raoyongming/HorNet)

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-09-05 06:12 UTC, Ezra-Yu commented
Great!  Thanks for your contribution!

2022-09-08 07:59 UTC, Ezra-Yu requested changes
1. please add the model in [`doc/apis/models.rst`](https://github.com/open-mmlab/mmclassification/blame/master/docs/en/api/models.rst) #backbone so that you can view your model docstring in the doc by clicking the link in the PR page.
![image](https://user-images.githubusercontent.com/18586273/189054926-40923786-bd42-4a4e-b230-d2a12784be3d.png)
2.  you can add convert script in `tools/convert_models/` folder since there are many checkpoints.

2022-09-08 07:59 UTC, Ezra-Yu commented on mmcls/models/backbones/hornet.py
> +                         's': 1 / 3}),
I think this value can move into the backbone class  as `scale`

2022-09-08 07:59 UTC, Ezra-Yu commented on mmcls/models/backbones/hornet.py
> +        dims = [
```
base_dim = self.arch_settings['base_dim']
dims = list(map(lambda x : 2**x * base_dim, range(4)))
```

2022-09-08 07:59 UTC, Ezra-Yu commented on mmcls/models/backbones/hornet.py
> +        dp_rates = [
use `dpr` for consistency with other implementations.

2022-09-08 09:55 UTC, okotaku commented on configs/hornet/metafile.yml
> +      FLOPs: 87260000            # 87.26M
VAN metafile has same problem. I will fix both.

2022-09-08 10:34 UTC, okotaku commented on mmcls/models/backbones/hornet.py
> +            Default to 5
Sounds good.

2022-09-09 16:06 UTC, Ezra-Yu approved these changes
LGTM.

2022-09-27 02:37 UTC, merged