[Feature] Support HorNet Backbone for dev1.x
open-mmlab/mmclassification pull request #1094
Opened 2022-10-14 03:58 UTC by okotaku

## Motivation

Related PR: https://github.com/open-mmlab/mmclassification/pull/1013

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-10-18 09:13 UTC, mzr1996 commented
Please merge the latest `dev-1.x` branch.
Because #1064 is merged, please remove the `num_classes` argument in the `Mixup` and `CutMix`, and the argument is handled by `data_preprocessor` now.

2022-11-01 08:59 UTC, Ezra-Yu requested changes
The old-style optimizer has been deprecated, Now use the [optim_wrapper](https://mmclassification.readthedocs.io/en/1.x/advanced_guides/schedule.html).

2022-11-01 08:59 UTC, Ezra-Yu commented on configs/hornet/hornet-base-gf_8xb64_in1k.py
> +optimizer_config = dict(grad_clip=dict(max_norm=1.0), _delete_=True)
```suggestion
optim_wrapper=dict(
     optimizer = dict(lr=4e-3),
     clip_grad=dict(max_norm=100.0)
)
```

2022-11-01 08:59 UTC, Ezra-Yu commented on configs/hornet/hornet-base_8xb64_in1k.py
> +optimizer_config = dict(grad_clip=dict(max_norm=5.0), _delete_=True)
```suggestion
optim_wrapper=dict(
     optimizer = dict(lr=4e-3),
     clip_grad=dict(max_norm=100.0)
)
```

2022-11-01 08:59 UTC, Ezra-Yu commented on configs/hornet/hornet-small-gf_8xb64_in1k.py
> +optimizer_config = dict(grad_clip=dict(max_norm=1.0), _delete_=True)
```suggestion
optim_wrapper=dict(
     optimizer = dict(lr=4e-3),
     clip_grad=dict(max_norm=100.0)
)
```

2022-11-04 04:40 UTC, okotaku commented
@Ezra-Yu Thank you!

2022-11-04 07:30 UTC, Ezra-Yu approved these changes
LGTM.

2022-11-04 07:33 UTC, merged