1.x Multi task
open-mmlab/mmclassification pull request #1229
Opened 2022-11-25 17:21 UTC by piercus

## Motivation

This PR is an 1.x updated version of https://github.com/open-mmlab/mmclassification/pull/675 and https://github.com/open-mmlab/mmclassification/pull/808

The main idea is to provide a generic and flexible multi-task toolbox.

This is made basically for mmclassification, but it has made with the purpose to extend this tool to other mmlab project (mmdet, mmpose ...) to mix different type of task in the same joint training.

One of the main change compared to #675 is to take into account some inhomogenous dataset.

In an inhomogenous dataset, sample may have ground truth value for one task, but not for another task, and we need to use mask in the mult-task training logic in order to modulate which sample to take into account with which loss.

## Modification

Modifications are : 
* Dataset `MultiTaskDataset` + unit tests
* Pipeline `FormatMultiTaskLabels` + unit tests
* Metric `MultiTaskMetric` + unit tests
* Head `MultiTaskHead` + unit tests
* Structure `MultiTaskDataSample` + unit tests

## BC-breaking (Optional)

No

## Use cases (Optional)

### Simple use case

The basic use case here it to classify multiple classes using the same neural network.

This can be useful if you want to "superclass" ImageNet for example (see https://robustness.readthedocs.io/en/latest/example_usage/custom_imagenet.html)

### Nested use case

If you have 4 classification task, 2 about classifying the background, and 2 about classiying the foreground, you can decide to organize your task like 
```
dict(type= 'MultiTaskHead', task_heads={
  "foreground": dict(type= 'LinearMultiTaskHead', task_heads={
    "foreground0": dict(type= 'LinearClsHead', num_classes=3),
    "foreground1": dict(type= 'LinearClsHead', num_classes=3)
  }),
  "background": dict(type= 'LinearMultiTaskHead', task_heads={
    "background0": dict(type= 'LinearClsHead', num_classes=3),
    "background1": dict(type= 'LinearClsHead', num_classes=3)
  })
})
```

By doing this, you can share layers between some tasks

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring
- [ ] example tutorials not done yet.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-11-28 04:34 UTC, Ezra-Yu commented
Are there any multi-task open-source datasets to test?

2022-11-28 08:45 UTC, piercus commented
@Ezra-Yu 

MEDIC seems to be a good choice : https://crisisnlp.qcri.org/medic/index.html

2022-11-29 14:39 UTC, piercus commented
@Ezra-Yu We have added an example config in `configs/mobilenet_v2/mobilenet_multi_task.py`

2022-11-30 08:01 UTC, mzr1996 commented
Good.
I will spend time reviewing it these days.

2022-12-09 15:51 UTC, piercus commented
@mzr1996 an eval_mask has been added please share your feedback

2022-12-16 14:34 UTC, mzr1996 requested changes

2022-12-16 14:34 UTC, mzr1996 commented on mmcls/models/heads/multi_task_head.py
> +        return data_samples
How about using the below method? Then we don't need to modify the `ClsHead` and I have tested to train and do validation it on a demo dataset.
```suggestion
        predictions_dict = dict()

        for task_name, head in self.task_heads.items():
            task_samples = head.predict(feats)
            batch_size = len(task_samples)
            predictions_dict[task_name] = task_samples

        if data_samples is None:
            data_samples = [MultiTaskDataSample() for _ in range(batch_size)]

        for task_name, task_samples in predictions_dict.items():
            for data_sample, task_sample in zip(data_samples, task_samples):
                task_sample.set_field(
                    task_name in data_sample.tasks,
                    'eval_mask',
                    field_type='metainfo')

                if task_name in data_sample.tasks:
                    data_sample.get(task_name).update(task_sample)
                else:
                    data_sample.set_field(task_sample, task_name)

        return data_samples
```

2022-12-19 06:05 UTC, mzr1996 approved these changes

2022-12-30 02:36 UTC, merged

2023-03-21 09:20 UTC, piercus commented
Thanks @marouaneamz for your work on this ! This has been a great internship :-)