Add clip backbone
open-mmlab/mmclassification pull request #1258
Opened 2022-12-12 11:50 UTC by Scarecrow0

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification
Add the CLIP backbone for inference time  of Imagenet classification.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-12-12 11:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=1258) it.</sub>

2022-12-12 14:18 UTC, tonysy commented on configs/clip/README.md
> +@misc{https://doi.org/10.48550/arxiv.2103.00020,
@InProceedings{pmlr-v139-radford21a,
  title = 	 {Learning Transferable Visual Models From Natural Language Supervision},
  author =       {Radford, Alec and Kim, Jong Wook and Hallacy, Chris and Ramesh, Aditya and Goh, Gabriel and Agarwal, Sandhini and Sastry, Girish and Askell, Amanda and Mishkin, Pamela and Clark, Jack and Krueger, Gretchen and Sutskever, Ilya},
  booktitle = 	 {Proceedings of the 38th International Conference on Machine Learning},
  year = 	 {2021},
  series = 	 {Proceedings of Machine Learning Research},
  publisher =    {PMLR},
}

2022-12-12 14:21 UTC, tonysy commented
The `configs/clip/vit_base_224_dataproc.py` and other similar files should be moved to `configs/_base_/datasets`, please follow the filename convention like `imagenet_bs64_clip_224.py`

2022-12-12 14:22 UTC, tonysy commented on configs/clip/vit_base_224_dataproc.py
> +# _base_ = ['./pipelines/rand_aug.py']
```suggestion
```

2022-12-12 14:22 UTC, tonysy commented on configs/clip/vit_base_384_dataproc.py
> +# _base_ = ['./pipelines/rand_aug.py']
```suggestion
```

2022-12-12 14:22 UTC, tonysy commented on configs/clip/vit_base_448_dataproc.py
> +# _base_ = ['./pipelines/rand_aug.py']
```suggestion
```

2022-12-12 14:24 UTC, tonysy commented on mmcls/models/backbones/vision_transformer.py
> +from ..builder import MODELS
```suggestion
from mmcls.registry import MODELS
```
Please explain the reason of the modification?

2022-12-12 14:24 UTC, tonysy requested changes
As inline comments

2022-12-13 02:57 UTC, mzr1996 commented on configs/clip/metafile.yml
> +  - Name: vit_base_patch16_clip_384.openai_ft_in12k_in1k
Please rename the model name according to https://mmclassification.readthedocs.io/en/dev-1.x/advanced_guides/convention.html
For example:
`clip-vit-base-p16_openai-pre_3rdparty_in1k`
`clip-vit-base-p16_laion2b-in12k-pre_3rdparty_in1k-384px`

2022-12-14 13:01 UTC, Scarecrow0 commented
> As inline comments

Changes are applied.

2022-12-15 03:23 UTC, tonysy commented on configs/clip/metafile.yml
> +Collection:
```suggestion
Collections:
```

2022-12-15 03:53 UTC, Scarecrow0 commented
Request for further review. @mzr1996 

The directory of converted checkpoints for CLIP model: /mnt/petrelfs/share_data/lirongjie/clip_backbone_ckpt

2022-12-19 09:52 UTC, mzr1996 requested changes

2022-12-19 09:52 UTC, mzr1996 commented on configs/clip/metafile.yml
> +  - Name: clip-vit-base-p16_openai_3rdparty_ft_in12k_in1k-224px
Here, the name should be `clip-vit-base-p16_openai-in12k-pre_3rdparty_in1k`
1. Both OpenAI and in12k are used for pre-training, which should be placed at the second section.
2. `ft` is unnecessary.
3. `224px` is usually default setting, and we only specify it when it's not 224px.

2022-12-19 09:52 UTC, mzr1996 commented on configs/clip/metafile.yml
> +      FLOPs: 16855600128.0
Flops should be an int number.

2022-12-19 09:52 UTC, mzr1996 commented on configs/clip/metafile.yml
> +    Config: configs/clip/vit-base-p16_pt-64xb64_in1k-224.py
The config name should be `vit-base-p16_64xb64_in1k.py`. You don't need `pt` to specify a config for pre-train or fine-tuning by now.
And if the image size is not 224px, please use name like `vit-base-p16_64xb64_in1k-384px.py`

2022-12-19 09:52 UTC, mzr1996 requested changes

2022-12-19 09:52 UTC, mzr1996 commented on configs/clip/metafile.yml
> +    In Collections: CLIP
`In Collection`, instead of `In Collections`.

2022-12-19 13:54 UTC, tonysy requested changes
Please upadte the files according to zerun's comments

2022-12-22 08:32 UTC, mzr1996 approved these changes

2022-12-22 08:33 UTC, merged