[Fix] Support dynamic topk when num_classes < 5
open-mmlab/mmclassification pull request #1263
Opened 2022-12-13 11:24 UTC by jamiechoi1995

Fix #810, #667

When num_classes < 5, it will raise

```python
RunTimeError: selected index k out of range
```

One possible solution is to specify the topk value in config file:
```python
evaluation = dict(interval=1, metric='accuracy', metric_options={'topk': 1})
```

However, this PR propose a better solution, which is to calculate the topk value dynamically.

2022-12-13 11:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=1263) it.</sub>

2022-12-13 13:19 UTC, Ezra-Yu commented
Please sign the CLA, so that we can review this PR.

2022-12-13 14:15 UTC, jamiechoi1995 commented
> Please sign the CLA, so that we can review this PR.

Signed, thanks for the reminder.

2022-12-14 05:23 UTC, mzr1996 approved these changes
Looks good

2022-12-14 05:26 UTC, mzr1996 requested changes
Hello, I think when `num_classes` less than 5, we can directly set the default topk as `(1, )` instead of `(1, maxk)`, because the topk-maxk result should be always 100%

2022-12-14 05:26 UTC, mzr1996 commented on mmcls/datasets/base_dataset.py
> +        maxk = min(5, len(results[0]))
maybe directly use
```suggestion
        default_topk = (1, 5) if len(results[0]) > 5 else (1, )
```

2022-12-14 05:26 UTC, mzr1996 commented on mmcls/datasets/base_dataset.py
> +            metric_options = {'topk': (1, maxk)}
And here, use
```suggestion
            metric_options = {'topk': default_topk}
```

2022-12-14 07:10 UTC, jamiechoi1995 commented
> Hello, I think when `num_classes` less than 5, we can directly set the default topk as `(1, )` instead of `(1, maxk)`, because the topk-maxk result should be always 100%

looks good to me.

2023-02-06 09:03 UTC, jamiechoi1995 commented
I have passed all the unit tests on my local machine and I have no idea why the online unit test failed, would anyone be able to help me take a look at this? @mzr1996 
![图片](https://user-images.githubusercontent.com/13494034/216929473-20925af9-cca4-4b5f-b5ec-1d41ba238614.png)

2023-04-06 12:54 UTC, closed without merging