[Fix] adapt to matplotlib fig 1px precision lost
open-mmlab/mmclassification pull request #1271
Opened 2022-12-16 09:19 UTC by ZonePG

## Motivation

on my m1 mac, when I run example https://github.com/wangruohui/sjtu-openmmlab-tutorial/blob/main/cls-2-train.ipynb

encounter error is that

```
Traceback (most recent call last):
  File "cls-1-inference.py", line 72, in <module>
    show_result_pyplot(model, 'banana.png', result)
  File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/apis/inference.py", line 114, in show_result_pyplot
    model.show_result(
  File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/models/classifiers/base.py", line 212, in show_result
    img = imshow_infos(
  File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 333, in imshow_infos
    _, img = manager.put_img_infos(
  File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 270, in put_img_infos
    img_rgba = buffer.reshape(height, width, 4)
ValueError: cannot reshape array of size 630336 into shape (403,393,4)
```

origin image is `403 * 393`, but buffer 630336 shape would be `402 * 392 * 4`, 1 px precision lost occurs.

I found it's still 1 px precision lost after add EPS(0.01) after execute https://github.com/open-mmlab/mmclassification/blob/48fdcdbf76907f72a5aa167df94a618154783694/mmcls/core/visualization/image.py#L253

in https://github.com/matplotlib/matplotlib/issues/15363 discussions, it seems inevitable.

Can we make the `buffer.reshape` adapt to 1px precision?

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-12-16 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=1271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=1271) it.</sub>

2022-12-16 10:54 UTC, mzr1996 commented
Interesting update, I need some time to check it. And please fix the failed lint, thanks~

2022-12-16 16:00 UTC, ZonePG commented
lint failed as follows
```
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-yapf.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat:linkify-it-py,mdformat-openmmlab>=0.0.4,mdformat_frontmatter.
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
[INFO] Initializing environment for https://github.com/myint/docformatter.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    ssh: connect to host github.com port 22: Connection timed out
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
Check the log at /home/circleci/.cache/pre-commit/pre-commit.log

Exited with code exit status 3

```

2022-12-16 16:05 UTC, ZonePG commented
I run `pre-commit` passed on my local m1 mac machine.
repo workflow lint failed as follows, is it a problem with the network delay of the repo CI? Thanks.
```
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-yapf.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat:linkify-it-py,mdformat-openmmlab>=0.0.4,mdformat_frontmatter.
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
[INFO] Initializing environment for https://github.com/myint/docformatter.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    ssh: connect to host github.com port 22: Connection timed out
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
Check the log at /home/circleci/.cache/pre-commit/pre-commit.log

Exited with code exit status 3
CircleCI received exit code 3
```

2022-12-19 04:59 UTC, mzr1996 requested changes

2022-12-19 04:59 UTC, mzr1996 commented on mmcls/core/visualization/image.py
> +        self.fig_save.set_size_inches(width / dpi, height / dpi)
Let us reserve the `EPS` because it can avoid the precision lost in most situations.

2022-12-19 04:59 UTC, mzr1996 commented on mmcls/core/visualization/image.py
> +
```python
        stream, (buffer_w, buffer_h) = self.fig_save.canvas.print_to_buffer()
        buffer = np.frombuffer(stream, dtype='uint8')

        # The `EPS` won't solve all precision lost problems, therefore we don't
        # use origin height and width to reshape the buffer but use the buffer
        # shape. These may cause shape difference between the input and output.
        img_rgba = buffer.reshape(buffer_h, buffer_w, 4)

2022-12-19 11:03 UTC, ZonePG commented
Thanks~ Your consideration is more reasonable! I have fixed it.

2022-12-30 07:51 UTC, mzr1996 approved these changes

2022-12-30 07:52 UTC, merged