[Refactor] Refactor ClsDatasample to a union DataSample.
open-mmlab/mmclassification pull request #1371
Opened 2023-02-21 04:02 UTC by mzr1996

## Motivation

In this PR, I removed the `ClsDataSample` and replace it with `DataSample` for the classification task and the self-sup task, maybe multi-modal tasks in the future.

And I simply the structure of the data sample, abandon the `LabelData`, and replace it with `torch.Tensor`.

**previous**:
```python
ClsDataSample
- gt_label (LabelData)
  - label (torch.Tensor)
  - score (torch.Tensor)
- pred_label (LabelData)
  - label (torch.Tensor)
  - score (torch.Tensor)
```
**now**:
```python
DataSample
- gt_label (torch.Tensor)
- gt_score (torch.Tensor)
- pred_label (torch.Tensor)
- pred_score (torch.Tensor)
- ...  # Any other fields, like `mask` for mask image modeling.
```

## BC-breaking

Yes, you need to rename `ClsDataSample` to `DataSample`, and handle the structure modification of data samples in heads, metrics.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-02-21 09:01 UTC, fangyixiao18 requested changes

2023-02-21 09:01 UTC, fangyixiao18 commented on mmpretrain/structures/data_sample.py
> +
add `set_mask` function in this pr? It is a function in data_sample

2023-02-22 03:42 UTC, tonysy approved these changes
LGTM

2023-02-22 03:47 UTC, fangyixiao18 approved these changes

2023-02-23 02:07 UTC, merged