Riformer mmpt
open-mmlab/mmclassification pull request #1453
Opened 2023-04-03 13:12 UTC by techmonsterwang

Implementation of 'RIFormer: Keep Your Vision Backbone Effective But Removing Token Mixer'

2023-04-06 12:37 UTC, fangyixiao18 requested changes

2023-04-06 12:37 UTC, fangyixiao18 commented on configs/riformer/metafile.yml
> +      Version: v1.0.rc6
```suggestion
      Version: v1.0.0rc6
```

2023-04-06 12:37 UTC, fangyixiao18 commented on configs/riformer/README.md
> +Place the ImageNet dataset to the `data/imagenet/` directory, or prepare datasets according to the [docs](https://mmclassification.readthedocs.io/en/1.x/user_guides/dataset_prepare.html#prepare-datas
```suggestion
Place the ImageNet dataset to the `data/imagenet/` directory, or prepare datasets according to the [docs](https://mmpretrain.readthedocs.io/en/latest/user_guides/dataset_prepare.html#prepare-dataset).
```

2023-04-07 02:05 UTC, Ezra-Yu approved these changes
LGTM.

2023-04-07 02:32 UTC, merged