[Feature] Add translate pipeline
open-mmlab/mmclassification pull request #165
Opened 2021-02-25 02:36 UTC by LXXXXR

Hi,
In this pull request, Translate pipeline is added. 
This pull request serves as a sub-task for implementing auto-augmentation. 
Pipelines needed are listed below.
    - [x] Shear
    - [x] Translate
    - [ ] Rotate
    - [ ] AutoContrast
    - [ ] Invert
    - [ ] Equalize
    - [ ] Solarize
    - [ ] Posterize
    - [ ] Contrast
    - [ ] Color
    - [ ] Brightness
    - [ ] Sharpness
This pull request has conflicts with #163, I will resolve them after #163 is merged.
Please kindly take a look. Thank you.

2021-02-25 06:30 UTC, ycxioooong requested changes

2021-02-25 06:30 UTC, ycxioooong commented on tests/test_pipelines/test_auto_augment.py
> +    assert (results['img'] == translated_img).all()
Also, please check the test cases: https://github.com/open-mmlab/mmcv/blob/master/tests/test_image/test_geometric.py#L488

2021-02-25 08:00 UTC, ycxioooong approved these changes

2021-02-25 08:04 UTC, ycxioooong commented
@LXXXXR, there are conflicts now. You may check on your local updates. Or re-submit this PR. The conflicts are caused by both revising auto_augmetn.py, test_auto_augment.py and pipelines/__init__.py in two PRs.

2021-02-25 09:20 UTC, LXXXXR commented
> @LXXXXR, there are conflicts now. You may check on your local updates. Or re-submit this PR. The conflicts are caused by both revising auto_augmetn.py, test_auto_augment.py and pipelines/**init**.py in two PRs.

Conflicts are resolved now. Pls take a look. Thank you.

2021-02-26 03:48 UTC, ycxioooong approved these changes

2021-02-26 03:48 UTC, merged