add attribute 'test' in dict 'data'
open-mmlab/mmclassification pull request #264
Opened 2021-05-21 00:29 UTC by freepoet

when I implemented: 
`python tools/test.py configs/lenet/lenet5_mnist.py xxx.pth`,
a error was reported: 
` AttributeError: 'ConfigDict' object has no attribute 'test'
`
so I  add attribute 'test' in dict 'data'  in lenet5_mnist.py  by referring other config files.

2021-05-21 00:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=264) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=264) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=264) it.</sub>

2021-05-21 01:51 UTC, mzr1996 requested changes

2021-05-21 01:51 UTC, mzr1996 commented on configs/lenet/lenet5_mnist.py
> +    test = dict(
Please delete spaces around '='.

2021-05-21 02:24 UTC, mzr1996 approved these changes

2021-05-21 04:52 UTC, freepoet commented
sorry, I commit and push some custom files accidently. I will undo this commit later.

2021-05-21 06:00 UTC, ycxioooong commented
Hi @freepoet, the file location should not be custom/xxx/. Could you please relocate the config files into `mmclassification/configs`?

2021-05-21 12:18 UTC, freepoet commented
> Hi @freepoet, the file location should not be custom/xxx/. Could you please relocate the config files into `mmclassification/configs`?
> 
> I will start the review after the next commit :)

I deleted my wrong uploaded files(**custom/xxx/**) and make a new commit.

2021-05-29 02:49 UTC, ycxioooong approved these changes
LGTM

2021-05-31 02:19 UTC, merged