Add ECenterCrop and ERandomCrop
open-mmlab/mmclassification pull request #268
Opened 2021-05-25 10:37 UTC by LXXXXR

Hi,
This pull request implements 2 transforms: `ECenterCrop` and `ERandomCrop`. Pls kindly take a look. Thank you.
Ref: https://github.com/kakaobrain/fast-autoaugment/blob/master/FastAutoAugment/data.py

2021-05-25 10:47 UTC, mzr1996 commented
So what's the meaning of "EfficientNet style"? What's the difference between it and the original version

2021-05-25 11:13 UTC, LXXXXR commented
> So what's the meaning of "EfficientNet style"? What's the difference between it and the original version

I guess it is quite confusing to users. I have updated the docstring accordingly.

2021-05-27 02:01 UTC, mzr1996 requested changes

2021-05-28 06:38 UTC, mzr1996 approved these changes
LGTM

2021-05-29 02:20 UTC, ycxioooong commented on mmcls/datasets/pipelines/transforms.py
>                  return xmin, ymin, target_height, target_width
if ymax, xmax are not returned, why do we need to calculate them?

2021-05-31 06:10 UTC, ycxioooong approved these changes
LGTM

2021-05-31 06:10 UTC, merged