[Feature] Add torchscript deployment
open-mmlab/mmclassification pull request #279
Opened 2021-05-31 02:51 UTC by AllentDan

Hi, this is a PR for adding TorchScript deployment.
Added tracing judgements to cls_head, linear_head, multi_label_head, multi_label_linear_head and vision_transformer_head.
Added pytorch2torchscript.py.
Added pytorch2torchscript.md

2021-06-02 03:27 UTC, mzr1996 approved these changes
LGTM

2021-06-04 09:18 UTC, ycxioooong requested changes

2021-06-04 09:18 UTC, ycxioooong commented on tools/deployment/pytorch2torchscript.py
> +        trace_model.save(output_file)
`model.save` does not check if the specified folder exists. 
When I tested the script with a non-existed path `some-non-exists-folder/model-name`, the runtime error occurred.
We'd better first check if the output_file path is valid.

2021-06-12 13:50 UTC, ycxioooong approved these changes
LGTM now

2021-06-12 13:50 UTC, merged