Fix init_weights bug in shufflenet
open-mmlab/mmclassification pull request #318
Opened 2021-06-22 03:05 UTC by Ezra-Yu

1. Fix bug in shufflenet.When using init_cfg("pretrain", "xxx"),the loaded weight will be overwritten.
2.refactor the init_weights in mobilenetv2

2021-06-23 10:11 UTC, mzr1996 requested changes

2021-06-23 10:11 UTC, mzr1996 commented on mmcls/models/backbones/shufflenet_v1.py
> +            super(ShuffleNetV1, self).init_weights(self.init_cfg)
If the users pass `init_cfg=None` to `ShuffleNet`, this method will continue to use the default init method. It will be confusing.

2021-06-29 09:44 UTC, mzr1996 approved these changes
Modified some code after discussion with Zheng Miao and Shilong.

2021-06-30 11:41 UTC, ycxioooong approved these changes
LGTM

2021-06-30 11:41 UTC, merged