Update test.py
open-mmlab/mmclassification pull request #441
Opened 2021-09-12 08:29 UTC by zhaoxin111

## Motivation

Fix the output format error when metric-options is specified

## Modification

Add metric-options judgment condition
## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2021-09-12 08:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=441) it.</sub>

2021-09-13 02:07 UTC, mzr1996 commented
Thanks for your contribution, we will review it recently.

2021-09-18 10:28 UTC, mzr1996 requested changes

2021-09-18 10:28 UTC, mzr1996 commented on tools/test.py
> +                    v = [round(out, 2) for out in v.tolist()]
According to my understanding, the problem is the result format doesn't support `np.ndarray`.
My suggestion:
```suggestion
                if isinstance(v, np.ndarray):
                    v = [round(out, 2), for out in v.tolist()]
                elif isinstance(v, Number):
                    v = round(v, 2)
                else:
                    raise ValueError(f'Unsupport metric type: {type(v)}')
```

2021-09-19 16:48 UTC, Junjun2016 commented
Hi @zhaoxin111 
Please fix the lint error.

2021-09-24 01:38 UTC, mzr1996 requested changes

2021-09-24 01:38 UTC, mzr1996 commented on tools/test.py
> +                else:
double `else`?

2021-09-28 09:49 UTC, mzr1996 requested changes
Please fix the lint problem.

2021-09-28 09:49 UTC, mzr1996 commented on tools/test.py
>  import warnings
```suggestion
import os
import warnings
from numbers import Number
```

2021-09-29 03:39 UTC, mzr1996 commented
Thanks! please sign the CLA before we can merge it.

> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=441) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=441) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=441) it.

2021-09-29 03:51 UTC, mzr1996 approved these changes
Good

2021-09-29 03:51 UTC, merged