Add tool to visualize LR schedule
open-mmlab/mmclassification pull request #498
Opened 2021-10-21 13:08 UTC by Ezra-Yu

## Motivation

before run a task, know what the learning rate would change along the task.
add a tool to visualize LR schedule

## Modification

mv function tools.analysis_tools.analyze_logs.load_json_logs to mmcls.utils.logger
add a tool to visualize LR schedule

## BC-breaking (Optional)

No

## Use cases (Optional)

```python tools/visualizations/vis_lr.py configs/resnet/resnet50_b16x8_cifar100.py```

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

2021-11-02 02:51 UTC, mzr1996 requested changes

2021-11-02 02:51 UTC, mzr1996 commented on docs/tools/visualization.md
> +python tools/visualizations/vis_lr.py configs/swin_transformer/swin_base_384_evalonly_imagenet.py --dataset-size 1100000 --save-path ./swin_lr_polt.jpg
```suggestion
python tools/visualizations/vis_lr.py configs/swin_transformer/swin_tiny_224_b16x64_300e_imagenet.py --dataset-size 1281167 --ngpus 8 --save-path ./swin_lr_polt.jpg
```

2021-11-02 02:51 UTC, mzr1996 commented on docs/tools/visualization.md
> +When using Imganet, directly specify the size of Imganet, as below:
ImageNet

2021-11-02 02:51 UTC, mzr1996 commented on docs_zh-CN/tools/visualization.md
> +当数据集为 Imganet 时，通过直接指定数据集大小来节约时间，并保存图片：
ImageNet

2021-11-02 02:51 UTC, mzr1996 commented on docs_zh-CN/tools/visualization.md
> +python tools/visualizations/vis_lr.py configs/swin_transformer/swin_base_384_evalonly_imagenet.py --dataset-size 1100000 --save-path ./swin_lr_polt.jpg
Same

2021-11-02 03:34 UTC, Ezra-Yu commented on docs/tools/visualization.md
> +When using Imganet, directly specify the size of Imganet, as below:
fixed

2021-11-03 02:47 UTC, mzr1996 approved these changes
LGTM

2021-11-03 02:48 UTC, merged