Update model_zoo.md
open-mmlab/mmclassification pull request #607
Opened 2021-12-16 14:19 UTC by NickChang97

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification
Fix typo
Please briefly describe what modification is made in this PR.
add missed info
## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2021-12-16 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=607) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=607) it.</sub>

2021-12-17 07:19 UTC, Ezra-Yu commented
Thank you for your contribution, it is very kind of you to help us fix it.

2021-12-17 07:26 UTC, Ezra-Yu requested changes
1. the links in [`configs/deit/readme.md`](https://github.com/open-mmlab/mmclassification/tree/master/configs/deit)  and [`configs/conformer/readme.md`](https://github.com/open-mmlab/mmclassification/tree/master/configs/conformer) should be also chnaged.

2021-12-17 07:26 UTC, Ezra-Yu commented on docs/en/model_zoo.md
> +| DeiT-tiny\* | 5.72 | 1.08 | 72.13 | 91.13 | [config](../../configs/deit/deit-tiny_pt-4xb256_in1k.py) | [model](https://download.openmmlab.com/mmclassification/v0/deit/deit-tiny_3rdparty_pt-4xb256_i
better to use absolute path, like `https://github.com/open-mmlab/mmclassification/blob/master/configs/deit/deit-tiny_pt-4xb256_in1k.py`

2021-12-17 07:55 UTC, mzr1996 commented
This problem has been fixed in https://github.com/open-mmlab/mmclassification/pull/593

2021-12-17 07:55 UTC, closed without merging