[BUG] Fix bug of vis-cam
open-mmlab/mmclassification pull request #658
Opened 2022-01-18 05:51 UTC by Ezra-Yu

## Motivation

Fix bug in #654 , `support gram-cam==1.3.7`.

## Modification

Fix bug in #654 

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-01-18 08:19 UTC, mzr1996 requested changes
Better to develop based on #656

2022-01-18 08:19 UTC, mzr1996 commented on tools/visualizations/vis_cam.py
> +            warnings(f'You can using pytorch_grad_cam==1.3.6 : {e}')
unnecessary warning.

2022-01-18 08:50 UTC, Ezra-Yu commented on tools/visualizations/vis_cam.py
> +            warnings(f'You can using pytorch_grad_cam==1.3.6 : {e}')
done.

2022-01-19 11:01 UTC, Ezra-Yu commented
close due to #656

2022-01-19 11:01 UTC, closed without merging