Support Stanford Car dataset
open-mmlab/mmclassification pull request #893
Opened 2022-07-05 03:40 UTC by zzc98

## Motivation

Support [Stanford Car dataset](https://ai.stanford.edu/~jkrause/cars/car_dataset.html) .

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-07-05 03:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmclassification?pullRequest=893) before we can accept your contribution.<br/><hr/>**zhuyu2** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmclassification?pullRequest=893) it.</sub>

2022-07-12 11:06 UTC, Ezra-Yu commented on mmcls/datasets/stanford_car.py
> +    """The Stanford Car Dataset. Support the `Stanford Car.
There are some errors with the format

https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/datasets/mnist.py#L18

2022-07-12 11:06 UTC, Ezra-Yu commented on mmcls/datasets/stanford_car.py
> +        if test_mode:
here `test_mode` is redundant, just use `ann_file` to specificy phase.

2022-07-12 11:06 UTC, Ezra-Yu commented on configs/resnet/resnet50_8xb8_stanford_car.py
> +    '../_base_/schedules/stanford_car_bs8.py', '../_base_/default_runtime.py'
missing this file '../_base_/schedules/stanford_car_bs8.py'

2022-08-15 02:20 UTC, Ezra-Yu approved these changes
LGTM.

2022-08-15 02:52 UTC, mzr1996 requested changes

2022-08-15 02:52 UTC, mzr1996 commented on requirements/runtime.txt
> +scipy
Please move the `scipy` to the optional requirement file.

2022-08-15 02:52 UTC, mzr1996 commented on mmcls/datasets/stanford_car.py
> +            data = sio.loadmat(self.train_ann_file)
Please import `scipy.io` only when using it. The `scipy` package is a little large, and if we only use it in a dataset class, don't make it a required package.

2022-08-15 02:53 UTC, mzr1996 commented on mmcls/datasets/stanford_car.py
> +            data = sio.loadmat(self.train_ann_file)
Same in the unit tests.

2022-08-16 02:50 UTC, mzr1996 approved these changes

2022-08-16 03:14 UTC, merged

2023-04-04 10:26 UTC, OpenMMLab-Team commented
Hi @zzc98 ！First of all, we want to express our gratitude for your significant PR in the MMClassification project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution！❤