Mobile one
open-mmlab/mmclassification pull request #966
Opened 2022-08-12 03:35 UTC by Ezra-Yu

## Motivation

Add MobileOne backbone, 
[Paper](https://arxiv.org/abs/2206.04040)
[Github](https://github.com/apple/ml-mobileone)

## Note

*Because the [official repo.](https://github.com/apple/ml-mobileone) does not give a strategy for training and testing, the test data pipline of [RepVGG](https://github.com/open-mmlab/mmclassification/tree/master/configs/repvgg) is used here, and the result is about 0.1 lower than the official one. Refer to [this issue](https://github.com/apple/ml-mobileone/issues/2).*

## Use cases (Optional)
```
    Example:
        >>> from mmcls.models import MobileOne
        >>> import torch
        >>> model = MobileOne("s0", out_indices=(0, 1, 2, 3))
        >>> model.eval()
        >>> x = torch.rand(1, 3, 224, 224)
        >>> outputs = model(x)
        >>> for out in outputs:
        ...     print(tuple(out.shape))
        (1, 48, 56, 56)
        (1, 128, 28, 28)
        (1, 256, 14, 14)
        (1, 1024, 7, 7)
```
## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-09-05 01:10 UTC, mzr1996 requested changes

2022-09-05 01:10 UTC, mzr1996 commented on mmcls/models/backbones/mobileone.py
> +        stride (int): Stride of convolution layers. Default: 1.
Please check all default values in the docstring, and use `defaults to xxx`.

2022-09-05 01:10 UTC, mzr1996 commented on mmcls/models/backbones/mobileone.py
> +            Default: dict(type='BN', requires_grad=True).
```suggestion
            Defaults to ``dict(type='BN', requires_grad=True)``.
```

2022-09-05 01:10 UTC, mzr1996 commented on mmcls/models/backbones/mobileone.py
> +                 in each stage.
The item in a list should be aligned left.
```suggestion
            - num_conv_branches (Sequence[float]): Number of conv branches
              in each stage.
```

2022-09-05 01:10 UTC, mzr1996 commented on tools/convert_models/mobileone_to_mmcls.py
> +        'MMClassification style.')
Fix the description

2022-09-05 01:10 UTC, mzr1996 commented on tools/convert_models/mobileone_to_mmcls.py
> +        # timm checkpoint
remove the comment

2022-09-05 01:10 UTC, mzr1996 commented on tools/convert_models/mobileone_to_mmcls.py
> +def convert_twins(args, ckpt):
convert `twins`?

2022-09-05 01:11 UTC, mzr1996 commented
Please add it to the `model-zoo.md` and `models.rst`.

2022-12-15 04:00 UTC, Ezra-Yu commented
close it due to the branch dev-a.x have supported it.

2022-12-15 04:00 UTC, closed without merging