[Docs] Add Inference Doc
open-mmlab/mmclassification pull request #999
Opened 2022-08-26 11:07 UTC by Ezra-Yu

## Motivation

Add Inference Doc

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-30 02:42 UTC, mzr1996 requested changes

2022-08-30 02:42 UTC, mzr1996 commented on docs/en/user_guides/inference.md
> +## Inference on given image
a given image

2022-08-30 02:42 UTC, mzr1996 commented on docs/en/user_guides/inference.md
> +MMClassification provides high-level Python APIs for inference on given image:
a given image

2022-08-30 02:42 UTC, mzr1996 commented on docs/en/user_guides/inference.md
> +If you use mmcls as a 3rd-party package, you need to download the conifg and the demo image in the example.
conifg -> config

2022-08-30 03:57 UTC, Ezra-Yu commented on docs/en/user_guides/inference.md
> +MMClassification provides high-level Python APIs for inference on given image:
done.

2022-08-31 05:41 UTC, mzr1996 requested changes

2022-08-31 05:41 UTC, mzr1996 commented on docs/zh_CN/user_guides/inference.md
> +下面是一个示例，如何使用一个 ImageNet-1k 预训练权重初始化模型并推里给定图像。
推里->推理

2022-08-31 05:41 UTC, mzr1996 commented on docs/zh_CN/user_guides/inference.md
> +# 如何使用已有模型推理
```suggestion
# 使用现有模型推理
```

2022-08-31 05:41 UTC, mzr1996 commented on docs/zh_CN/user_guides/inference.md
> +## 对给定图像的推理
```suggestion
## 推理单张图片
```

2022-08-31 06:21 UTC, mzr1996 approved these changes

2022-08-31 06:21 UTC, merged